<section class="row w-100 m-auto vh-100">
    <div class="col-md-3 m-auto offset-md-4">
        <div class="card card-body">
            <form action="" method="post">
                <input name="email" type="email" placeholder="Email" class="form-control form-control-lg mb-3">

                <input name="senha" type="password" placeholder="Senha" class="form-control form-control-lg mb-3">

                <div class="d-grid">
                    <button class="btn btn-dark btn-lg">Entrar</button>
                </div>
            </form>
        </div>

        <?php App\Notification\WebNotification::show(); ?>
    </div>
</section>