<section class="container-fluid">
    <div class="d-flex mx-auto mt-5">
        <div class="d-flex flex-column align-items-center m-auto">
            <h1 class="fw-bold">SAE</h1>
            <div style="height: 0.16em" class="w-100 bg-dark">
                .
            </div>
            <span class="fs-4 mb-1">Sistema de Acompanhamento Escolar</span>
        </div>
        <div class="w-50 h-50">
            <img class="w-75 h-75" src="./assets/imagem.png" alt="">
        </div>
    </div>
</section>