<section class="card card-body container-fluid">
    <h1 class="text-center">Listar alunos:</h1>
    <hr>
    <div class="mt-2 w-100 d-flex justify-content-end">
        <a href="/alunos/novo"class="btn btn-outline-primary me-1">Adicionar aluno</a>
        <a href="/alunos/relatorio"class="btn btn-outline-primary">Gerar PDF</a>
    </div>
    
    <table class="table table-striped table-hover table-bordered align-middle text-center mt-4">
    <caption>Tabela de alunos</caption>
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Matricula</th>
                <th>Email</th>
                <th>Status</th>
                <th>Gênero</th>
                <th>Data de Nascimento</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($alunos ?? [] as $cadaAluno)
                {
                    echo "
                        <tr>
                            <td class='fw-bold'>{$cadaAluno->id}</td>
                            <td>{$cadaAluno->nome}</td>
                            <td>{$cadaAluno->cpf}</td>
                            <td>{$cadaAluno->matricula}</td>
                            <td>{$cadaAluno->email}</td>
                            <td>{$cadaAluno->status}</td>
                            <td>{$cadaAluno->genero}</td>
                            <td>{$cadaAluno->dataNascimento}</td>
                            <td>
                                <button class='btn btn-warning'>Editar</button>
                                <button class='btn btn-danger'>Excluir</button>
                            </td>
                        </tr>
                    ";
                }
            ?>
        </tbody>
    </table>
</section>