<section class="mt-3 card card-body container">
    <h1>Listar alunos:</h1>
    <div class="mt-2">
        <a href="alunos/novo"class="btn btn-outline-dark">Adicionar aluno</a>
    </div>
    
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Matricula</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

    <table></table>
</section>