<?php
    $curso = $dados[0];
?>

<section class="card card-body">
    <h1>Editar curso</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome: </label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $curso->nome?>">
                <label for="cargaHoraria">Carga horaria:</label>
                <input name="cargaHoraria" type="number" id="cargaHoraria" class="form-control mb-3" value="<?php echo $curso->cargaHoraria?>">
                <label for="descricao">Descrição: </label>
                <input name="descricao" type="text" id="descricao" class="form-control mb-3" value="<?php echo $curso->descricao?>">
                <label for="categoria">Categoria: </label>
                <select name="categoria" id="categoria" class="form-select mb-3">
                    <?php
                    $categoriaExistente;
                    if($curso->categoria_id == $categorias['id'][0]){
                        $categoriaExistente = $categorias['nome'][0];
                    }
                    echo "<option disabled selected>{$categoriaExistente}</option>";
                    foreach($categorias as $cadaCategoria){
                        echo "
                        <option value='{$cadaCategoria->id}'>{$cadaCategoria->nome}</option>
                        ";
                    }
                    ?>
                </select>
                <button class="btn btn-outline-dark w-100">Enviar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>