<section class="card card-body container-fluid">
    <h1 class="text-center">Listar alunos:</h1>
    <hr>
    <div class="mt-2 w-100 d-flex justify-content-end ">
        <a href="/alunos/novo" class="btn btn-outline-primary me-1">Adicionar aluno</a>
        <a href="/alunos/relatorio" class="btn btn-outline-primary">Gerar PDF</a>
    </div>
    <div class="row">
        <div class="col-4">

        </div>
        <div class="col-8">
            <table class="table table-striped table-hover table-bordered align-middle text-center mt-4">
                <caption>Tabela de alunos</caption>
                <thead class="table-dark">
                    <tr>
                        <th>#ID</th>
                        <th>Nome</th>
                        <th>Modalidade de ensino</th>
                        <th>Formação</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</section>